input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  mutate {
    add_field => { "log_type" => "application" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "application-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}
